### ISSUE TITLE
Question and concern

### ISSUE THREAD

**Issue by ghost** [Lewisk3/UltimateClassicMinimap#1]
When I played this w/ Brutal Doom, it shows the blood and death animations, any way to disable that ? 
and you can add an option to Disable the Enemies on UC Minimap pls ?
Also, I have Textured Display enabled, but on the UC Minimap it's not

**Comment by Lewisk3** [comment]
> When I played this w/ Brutal Doom, it shows the blood and death animations, any way to disable that ?

Disable "Draw Projectiles". Brutal Doom's Blood actors have Projectile flag(s).

> and you can add an option to Disable the Enemies on UC Minimap pls ?

This can be achieved by disabling the Radar in the Options menu. (Or you can set the Range to 0)

> Also, I have Textured Display enabled, but on the UC Minimap it's not

I'm not quite sure that it's possible to replicate this behavior currently.
