### ISSUE TITLE
Typo on UCM options

### ISSUE THREAD

**Issue by ghost** [Lewisk3/UltimateClassicMinimap#4]
There are two X Position options, but one of them doesn't move the X position. The top "X Position" is right, but the bottom "X Position" actually moves the Y position. This should be a very simple fix, since it's very minor.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/40510256/212503503-c5d33755-919f-4cc1-bbd6-e342d955191f.png)

Reuploaded image due to me posting the incorrect image.

**Comment by Lewisk3** [comment]
No idea how I didn't notice this, lol.
Fixed.
